# -*- coding: utf-8 -*-
"""z+claude.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zg1ZUbQcVtFbLb4tF0clKdFXgaeXArHA

# 🌍 Earth Engine → NetCDF Exporter

**Generic, fault-tolerant pipeline** for downloading any Google Earth Engine
`ImageCollection` as **year-wise, CF-compliant NetCDF** files.

| Feature | Detail |
|---|---|
| **Any resolution** | 30 m CDL ↔ 300 km GRACE — auto-detected |
| **Any temporal frequency** | Daily, monthly, annual — aggregated per year |
| **CF-1.8 compliant** | Standard global attrs, coordinate metadata, clean encoding |
| **Resume on crash** | Skips years already exported to Drive |
| **Data integrity** | Pre-write validation + post-write re-read verification |
| **Compression** | zlib — dramatically smaller files |
| **Edge-case safe** | 1 image/year, SR-ORG CRS, complex polygons |

### Usage
1. Edit the **Configuration** cell (typically just `DATASET_ID`)
2. Upload / mount your shapefile
3. **Runtime → Run all** (`Ctrl+F9`)
4. Files appear in `Drive / MSUGWB / <dataset> /`
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = '/content/drive/MyDrive/high_plains_quifer.zip'
extract_path = '/content/ogallala_shp'

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Files extracted to:", extract_path)

# ╔════════════════════════════════════════════════════════════════╗
# ║  CONFIGURATION — edit this cell for each dataset run           ║
# ╚════════════════════════════════════════════════════════════════╝


# ── Dataset ──────────────────────────────────────────────────────
# Examples:
#   "USDA/NASS/CDL"                  30 m   annual
#   "GRIDMET/DROUGHT"                ~4 km  pentad
#   "MODIS/061/MCD12Q1"              500 m  annual
#   "MODIS/061/MOD13A3"              1 km   monthly
#   "NASA/GRACE/MASS_GRIDS/LAND"     ~300 km monthly
DATASET_ID = "MODIS/061/MOD13A3"   # dont eport CDL or other 30m products with this, or you do, then coordinates to float64
PROJECT_ID = "msugw-503806"

# ── Region of interest ───────────────────────────────────────────
SHAPEFILE_DIR = "/content/ogallala_shp"   # folder with .shp + sidecars
ROI_LABEL     = "Ogallala"                # used in filenames

# ── Output ───────────────────────────────────────────────────────
DRIVE_ROOT = "/content/drive/MyDrive/MSUGWB"

# ── Year range (None = auto-detect from collection metadata) ─────
YEAR_START = None
YEAR_END   = None

# ── Processing knobs ─────────────────────────────────────────────
DASK_WORKERS    = 43     # parallel threads (keep <= 6 for GEE quotas)

# For monthly/annual data (MODIS, CDL), 1024 is optimal.
# For daily data (GRIDMET), use 2048 to prevent Dask graph explosion.
CHUNK_XY = 1024 if "MODIS" in DATASET_ID or "CDL" in DATASET_ID else 512

CHUNK_XY        = 256    # dask spatial chunk size (pixels per dim)
COMPRESS_LEVEL  = 1      # zlib  0 = off · 9 = max
MAX_RETRIES     = 3      # per-year retries for transient errors
FORCE_OVERWRITE = False  # True → re-process files already on Drive

# ═════════════════════════════════════════════════════════════════
#  Install · Import · Authenticate · Mount Drive
# ═════════════════════════════════════════════════════════════════

!pip install -q xee xarray netcdf4 geopandas pyproj
!pip install -q h5netcdf

import os, sys, glob, time, shutil, logging, tempfile
from datetime import datetime, timezone

import numpy as np
import ee
import xarray as xr
import xee                       # registers the 'ee' xarray engine
from xee import helpers
import geopandas as gpd
import pyproj
import gc
import dask
import requests

# ── Logging ──
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    datefmt='%H:%M:%S',
)
log = logging.getLogger('gee_export')
logging.getLogger('urllib3.connectionpool').setLevel(logging.ERROR)

# ── HTTP pool (avoids dropped connections on long runs) ──
_adp = requests.adapters.HTTPAdapter(pool_connections=50, pool_maxsize=50)
_ses = requests.Session()
_ses.mount('https://', _adp)

# ── Dask ──
dask.config.set(scheduler='threads', num_workers=DASK_WORKERS)

# ── Google Drive ──
try:
    from google.colab import drive
    drive.mount('/content/drive')
except ImportError:
    log.info('Not on Colab -- Drive mount skipped')

# ── Earth Engine ──
ee.Authenticate()
ee.Initialize(project=PROJECT_ID)
log.info('Earth Engine ready  (project=%s)', PROJECT_ID)

# !pip show xee
# import inspect
# import xee

# # Print the exact source code of the open_dataset function
# print(inspect.getsource(xee.EarthEngineBackendEntrypoint.open_dataset))

# ═════════════════════════════════════════════════════════════════
#  Pipeline Functions
# ═════════════════════════════════════════════════════════════════

# ─── ROI ─────────────────────────────────────────────────────────

def load_roi(shapefile_dir, simplify_deg=0.001):
    '''Load shapefile -> dissolved EPSG:4326 geometry.'''
    paths = glob.glob(os.path.join(shapefile_dir, '**', '*.shp'), recursive=True)
    if not paths:
        raise FileNotFoundError(f'No .shp found in {shapefile_dir}')

    gdf = gpd.read_file(paths[0])
    if gdf.crs is None or gdf.crs.to_epsg() != 4326:
        gdf = gdf.to_crs(epsg=4326)

    roi = (gdf.geometry.union_all()
           if hasattr(gdf.geometry, 'union_all')
           else gdf.geometry.unary_union)

    try:
        import shapely as _shp
        nv = int(_shp.get_num_coordinates(roi))
    except Exception:
        nv = len(roi.wkt) // 20

    if nv > 50_000:
        roi = roi.simplify(simplify_deg, preserve_topology=True)
        log.warning('Simplified ROI from %s vertices (tol=%.4f deg)', f'{nv:,}', simplify_deg)
    else:
        log.info('ROI vertices: %s', f'{nv:,}')
    return roi


# ─── CRS & Scale ────────────────────────────────────────────────

import pyproj
import numpy as np

def build_grid_params(roi, grid_crs, nominal_m):
    '''Calculate exact crsTransform and dimensions to bypass GEE pyramiding.

    GEE Affine Transform format: (x_scale, 0, x_origin, 0, -y_scale, y_origin)
    Origin is the Top-Left corner of the bounding box.
    '''
    # 1. Get ROI bounds in EPSG:4326
    minx, miny, maxx, maxy = roi.bounds

    # 2. Transform bounds to the target grid CRS
    transformer = pyproj.Transformer.from_crs("EPSG:4326", grid_crs, always_xy=True)
    x1, y1 = transformer.transform(minx, miny)
    x2, y2 = transformer.transform(maxx, maxy)

    left, right = min(x1, x2), max(x1, x2)
    bottom, top = min(y1, y2), max(y1, y2)

    # 3. Calculate scale based on CRS units
    try:
        unit = pyproj.CRS.from_user_input(grid_crs).axis_info[0].unit_name
    except Exception:
        unit = 'degree'

    if unit == 'metre':
        scale_x = float(nominal_m)
        scale_y = float(nominal_m)
    else:
        # Degrees: Adjust X for latitude convergence
        lat_centroid = roi.centroid.y
        cos_lat = np.cos(np.radians(lat_centroid))
        scale_y = nominal_m / 111_320.0
        scale_x = scale_y / cos_lat if cos_lat > 0 else scale_y

    # 4. Construct the GEE Affine Transform
    # Must be a tuple. Origin is Top-Left. Y-scale is negative.
    crs_transform = (scale_x, 0.0, left, 0.0, -scale_y, top)

    # 5. Calculate exact grid dimensions in pixels
    width = int(np.ceil((right - left) / scale_x))
    height = int(np.ceil((top - bottom) / scale_y))

    log.info('Calculated Grid : %d x %d pixels', width, height)
    log.info('CRS Transform   : %s', crs_transform)

    # Use exactly what the source code signature demands:
    return {
        'crs': grid_crs,
        'crs_transform': crs_transform,
        'shape_2d': (width, height)  # <--- MUST BE this exact key
    }

def resolve_crs_and_scale(collection):
    '''Auto-detect native CRS + pixel scale. Always returns a standard
    EPSG code and scale in that CRS's units.

    Why this is critical
    --------------------
    * Custom WKT CRS strings (e.g. ERDAS "IMAGINE GeoTIFF") are parseable
      by pyproj but cause XEE to produce a mis-aligned grid, returning
      all-NaN data.
    * SR-ORG codes (e.g. MODIS Sinusoidal SR-ORG:6974) cannot be parsed
      by pyproj at all.
    This function resolves both cases to a well-known EPSG code.
    '''
    proj = collection.first().select(0).projection()
    info = proj.getInfo()
    native_crs = info.get('crs', 'EPSG:4326')
    nominal_m  = proj.nominalScale().getInfo()

    log.info('Native CRS    : %s', native_crs[:70])
    log.info('Nominal scale : %.1f m', nominal_m)

    resolved = 'EPSG:4326'   # ultimate fallback

    if native_crs.startswith('SR-ORG:'):
        log.warning('SR-ORG CRS (%s) -> EPSG:4326 fallback', native_crs)
    elif native_crs.startswith('EPSG:'):
        resolved = native_crs
        log.info('Already EPSG: %s', resolved)
    else:
        try:
            crs_obj = pyproj.CRS.from_user_input(native_crs)
            epsg = crs_obj.to_epsg()
            if epsg:
                resolved = f'EPSG:{epsg}'
                log.info('Resolved to EPSG:%d', epsg)
            elif crs_obj.axis_info and crs_obj.axis_info[0].unit_name == 'metre':
                resolved = 'EPSG:5070'
                log.warning('Metre-based CRS, no EPSG -> EPSG:5070 (CONUS Albers)')
            else:
                log.warning('No EPSG match -> EPSG:4326')
        except Exception as exc:
            log.warning('CRS parse error: %s -> EPSG:4326', exc)

    # Compute scale in resolved CRS units
    try:
        unit = pyproj.CRS.from_user_input(resolved).axis_info[0].unit_name
    except Exception:
        unit = 'degree'

    if unit == 'metre':
        x_scale = round(nominal_m, 2)
        y_scale = round(nominal_m, 2)
    else:
        # Get ROI latitude to adjust for longitude convergence
        lat_centroid = roi.centroid.y  # Assuming roi is passed in or globally available
        cos_lat = np.cos(np.radians(lat_centroid))

        y_scale = nominal_m / 111_320.0
        x_scale = y_scale / cos_lat if cos_lat > 0 else y_scale

    log.info('Output CRS: %s | X-scale: %.6g | Y-scale: %.6g', resolved, x_scale, y_scale)
    return resolved, (x_scale, y_scale) # Return a tuple

    log.info('Output CRS    : %s  |  scale = %.6g %s', resolved, scale, unit)
    return resolved, scale


# ─── Encoding ───────────────────────────────────────────────────

def strip_xee_encoding(ds):
    '''Bake valid scale/offsets into data, then clear ALL encoding.'''
    for name in list(ds.data_vars):
        enc = ds[name].encoding
        scale = enc.get('scale_factor', 1.0)
        offset = enc.get('add_offset', 0.0)
        fill_val = enc.get('_FillValue', None)

        # If a real data scale exists, apply it to the actual values
        if scale != 1.0 or offset != 0.0:
            ds[name] = ds[name] * scale + offset
            # Re-mask the original fill values (which are now scaled)
            if fill_val is not None:
                ds[name] = ds[name].where(ds[name] != fill_val * scale + offset)

        ds[name].encoding.clear()

    for name in list(ds.coords):
        if name in ds:
            ds[name].encoding.clear()
    return ds

def build_encoding(ds, compress_level=1, chunk_xy=256):
    enc = {}

    for var in ds.data_vars:
        is_int = np.issubdtype(ds[var].dtype, np.integer)

        # Dynamically build chunk size based on variable dimensions
        var_chunks = []
        for dim in ds[var].dims:
            if dim == 'time':
                var_chunks.append(1)
            elif dim in ('x', 'y'):
                var_chunks.append(chunk_xy)
            else:
                # Fallback for unknown dims
                var_chunks.append(1)

        chunksizes = tuple(var_chunks)

        if is_int:
            enc[var] = {
                'dtype': 'int16' if ds[var].dtype.itemsize <= 2 else 'int32',
                '_FillValue': -32768,
                'zlib': compress_level > 0,
                'complevel': compress_level,
                'chunksizes': chunksizes
            }
        else:
            enc[var] = {
                'dtype': 'float32',
                '_FillValue': np.float32(np.nan),
                'zlib': compress_level > 0,
                'complevel': compress_level,
                'chunksizes': chunksizes
            }

    for c in ds.coords:
        if c == 'time':
            enc[c] = {
                'dtype': 'int64', '_FillValue': None,
                'units': 'days since 1970-01-01 00:00:00',
                'calendar': 'proleptic_gregorian'
            }
        elif c in ('x', 'y'):
            enc[c] = {'dtype': 'float32', '_FillValue': None}
    return enc


# ─── CF Compliance ──────────────────────────────────────────────

def make_cf_compliant(ds, dataset_id, roi_label, grid_crs, year):
    '''Stamp CF-1.8 global + coordinate attributes.'''
    ds.attrs.update({
        'Conventions': 'CF-1.8',
        'title':  f'{dataset_id} -- {roi_label} ({year})',
        'source': f'Google Earth Engine: {dataset_id}',
        'history': f'Created {datetime.now(timezone.utc).isoformat()}',
        'crs': grid_crs,
    })

    if 'time' in ds.coords:
        ds['time'].attrs.update(axis='T', standard_name='time')

    try:
        is_proj = (pyproj.CRS.from_user_input(grid_crs)
                   .axis_info[0].unit_name == 'metre')
    except Exception:
        is_proj = False

    if 'x' in ds.coords:
        ds['x'].attrs.update(
            axis='X',
            standard_name='projection_x_coordinate' if is_proj else 'longitude',
            units='m' if is_proj else 'degrees_east',
        )
    if 'y' in ds.coords:
        ds['y'].attrs.update(
            axis='Y',
            standard_name='projection_y_coordinate' if is_proj else 'latitude',
            units='m' if is_proj else 'degrees_north',
        )
    return ds


# ─── Pre-Write Validation ──────────────────────────────────────

# def pre_write_check(ds, year):
#     '''Load a small centre sample and raise RuntimeError if all NaN.'''
#     var0 = list(ds.data_vars)[0]
#     da = ds[var0]
#     yd = next((d for d in ('y', 'latitude', 'lat') if d in da.dims), None)
#     xd = next((d for d in ('x', 'longitude', 'lon') if d in da.dims), None)
#     if not yd or not xd:
#         log.warning('[%d] Cannot find spatial dims -- skipping pre-check', year)
#         n_skip+=1
#         return

#     ny, nx = da.sizes[yd], da.sizes[xd]
#     w = min(100, ny // 4, nx // 4, 200)
#     if w < 1:
#         w = 1
#     yc, xc = ny // 2, nx // 2

#     idx = {}
#     if 'time' in da.dims:
#         idx['time'] = 0
#     idx[yd] = slice(max(0, yc - w), min(ny, yc + w))
#     idx[xd] = slice(max(0, xc - w), min(nx, xc + w))

#     sample = da.isel(**idx).compute().values
#     nf = int(np.isfinite(sample).sum())
#     log.info('[%d] Pre-write: %s / %s finite in centre', year,
#              f'{nf:,}', f'{sample.size:,}')

#     if nf == 0:
#         raise RuntimeError(
#             f'[{year}] ALL-NaN -- Earth Engine returned no valid pixels. '
#             'Verify CRS, geometry, and year availability.'
#         )
#     pct = 100.0 * nf / sample.size
#     if pct < 1.0:
#         log.warning('[%d] Only %.1f%% finite -- possible partial coverage', year, pct)

def pre_write_check(ds, year):
    var0 = list(ds.data_vars)[0]
    da = ds[var0]

    # Subsample the grid (e.g., every 10th pixel) to check for ANY valid data
    # This avoids the "donut hole" false positive
    sample = da.isel(time=0).coarsen(
        {d: max(1, da.sizes[d] // 50) for d in ('x', 'y') if d in da.dims},
        boundary='trim'
    ).max().compute() # .max() ignores NaNs

    if np.isfinite(sample).sum() == 0:
        raise RuntimeError(f'[{year}] ALL-NaN in subsample -- check ROI/CRS.')
    log.info('[%d] Pre-write check passed (finite values found).', year)

# ─── Post-Write Integrity Verification ─────────────────────────

def post_write_verify(filepath, expected_vars, year):
    '''Reopen the NetCDF from disk and verify:
      1. All bands present
      2. Time dim exists
      3. Coords finite
      4. No bogus scale_factor
      5. Data has finite values
    Returns (ok, message).
    '''
    try:
        vds = xr.open_dataset(filepath, chunks='auto')
    except Exception as e:
        return False, f'Cannot reopen: {e}'

    try:
        # All expected variables?
        missing = [v for v in expected_vars if v not in vds.data_vars]
        if missing:
            return False, f'Missing: {missing}'

        # Time dimension?
        if 'time' not in vds.dims:
            return False, 'No time dimension'

        # Coordinates finite?
        for c in vds.coords:
            v = vds[c].values
            if np.issubdtype(v.dtype, np.floating):
                if not np.all(np.isfinite(v)):
                    return False, f'Non-finite coord: {c}'

        # No bogus scale_factor?
        for v in expected_vars:
            sf = vds[v].encoding.get('scale_factor')
            if sf is not None and sf != 1.0:
                return False, f'scale_factor={sf} on {v}'

        # Data has finite values in centre?
        da = vds[expected_vars[0]]
        idx = {}
        if 'time' in da.dims:
            idx['time'] = 0
        for d in da.dims:
            if d != 'time':
                s = da.sizes[d]
                m = s // 2
                hw = min(50, s // 4, 100)
                if hw < 1:
                    hw = 1
                idx[d] = slice(max(0, m - hw), min(s, m + hw))
        samp = da.isel(**idx).compute().values
        nf = int(np.isfinite(samp).sum())
        if nf == 0:
            return False, 'All NaN on re-read'
        pct = 100.0 * nf / samp.size
        return True, f'{pct:.1f}% finite in verify sample'

    finally:
        vds.close()


import hashlib

def get_md5(filepath, chunksize=1024*1024*10):
    '''Calculate MD5 using O_DIRECT to bypass Linux Page Cache.'''
    import os
    import hashlib
    hash_md5 = hashlib.md5()
    # O_DIRECT bypasses kernel caching. Requires aligned reads.
    flags = os.O_RDONLY
    try:
        flags |= os.O_DIRECT  # Linux specific
    except AttributeError:
        pass # Colab on Mac/Windows fallback

    fd = os.open(filepath, flags)
    try:
        # Must read in multiples of 512 bytes for O_DIRECT
        aligned_chunk = chunksize - (chunksize % 512)
        with os.fdopen(fd, 'rb', buffering=0) as f:
            while True:
                chunk = f.read(aligned_chunk)
                if not chunk:
                    break
                hash_md5.update(chunk)
    finally:
        pass # fdopen closes the fd
    return hash_md5.hexdigest()

def robust_drive_copy(src, dst, max_retries=3):
    '''Copy file to Drive in chunks, flush OS buffers, verify MD5, and retry.'''
    src_md5 = get_md5(src)

    for attempt in range(1, max_retries + 1):
        try:
            log.info('Drive copy attempt %d/%d ...', attempt, max_retries)

            # 1. Copy in 10MB chunks
            with open(src, 'rb') as f_src, open(dst, 'wb') as f_dst:
                while True:
                    chunk = f_src.read(1024 * 1024 * 10)
                    if not chunk:
                        break
                    f_dst.write(chunk)

            # 2. Force OS to flush FUSE buffers to Google's servers
            # This is CRITICAL in Colab. Without it, Python moves on
            # before the file is actually uploaded, causing truncation.
            os.sync()
            time.sleep(5)  # Give FUSE a moment to update metadata

            # 3. Verify file size
            src_size = os.path.getsize(src)
            dst_size = os.path.getsize(dst)
            if src_size != dst_size:
                raise IOError(f'Size mismatch (src: {src_size}, dst: {dst_size})')

            # 4. Verify MD5 integrity
            dst_md5 = get_md5(dst)
            if src_md5 != dst_md5:
                raise IOError('MD5 hash mismatch (silent data corruption)')

            log.info('Copy verified successfully (MD5 match).')
            return True

        except Exception as e:
            log.error('Drive copy failed: %s', e)
            if os.path.exists(dst):
                os.remove(dst) # Clean up the corrupt partial file
                gc.collect()

            if attempt < max_retries:
                wait = 15 * attempt
                log.info('Retrying in %ds ...', wait)
                time.sleep(wait)
            else:
                raise RuntimeError(f'Failed to copy to Drive after {max_retries} attempts.')


def sanitize_attrs(ds):
    """Flatten complex GEE metadata to strings to prevent HDF5 write crashes."""
    for var in list(ds.data_vars) + list(ds.coords):
        if var in ds:
            for key, val in list(ds[var].attrs.items()):
                if not isinstance(val, (str, int, float, np.number)):
                    # Convert lists/dicts to string, or drop them
                    ds[var].attrs[key] = str(val)
    return ds

"""## 🚀 Pipeline Execution

The cell below processes **all years** sequentially:

1. **Resume check** — skips years whose `.nc` already exists on Drive
   (also detects corrupt partial files < 1 KiB and re-downloads them)
2. **Open via XEE** — lazy dask-backed dataset, no eager download
3. **Strip encoding** — removes the bogus `scale_factor` from CRS metadata
4. **CF compliance** — stamps standard global + coordinate attributes
5. **Pre-write validation** — loads a centre sample, aborts if all NaN
6. **Write to scratch** — `/content/` (fast local SSD) with zlib compression
7. **Post-write verification** — re-opens the file from disk, checks integrity
8. **Export to Drive** — only after verification passes

> **After a crash:** just *Run All* again — completed years are auto-skipped.
"""

# # ── 1. Collection metadata ──────────────────────────────────────
# coll = ee.ImageCollection(DATASET_ID)
# bands = coll.first().bandNames().getInfo()
# if not bands:
#     raise ValueError(f'{DATASET_ID} returned no bands')

# # ── 2. CRS & grid (get native scale) ────────────────────────────
# grid_crs, px = resolve_crs_and_scale(coll.select(bands))

# # ── 3. Load ROI with dynamic simplification ─────────────────────


# # ── 4. Output folder ────────────────────────────────────────────
# short = DATASET_ID.split('/')[-1]
# out_dir = os.path.join(DRIVE_ROOT, short)
# os.makedirs(out_dir, exist_ok=True)
# log.info('Output folder : %s', out_dir)

# ═════════════════════════════════════════════════════════════════
#  Run Pipeline
# ═════════════════════════════════════════════════════════════════

import gc

log.info('=' * 62)
log.info('  Dataset : %s', DATASET_ID)
log.info('=' * 62)

# ── 1. Collection metadata ──────────────────────────────────────
coll = ee.ImageCollection(DATASET_ID)
bands = coll.first().bandNames().getInfo()
if not bands:
    raise ValueError(f'{DATASET_ID} returned no bands')

try:
    y0 = YEAR_START or int(ee.Date(
        coll.sort('system:time_start').first()
            .get('system:time_start')).get('year').getInfo())
    y1 = YEAR_END or int(ee.Date(
        coll.sort('system:time_start', False).first()
            .get('system:time_start')).get('year').getInfo())
except Exception as exc:
    raise ValueError(
        f'Cannot determine year range for {DATASET_ID}: {exc}'
    ) from exc

years = list(range(y0, y1 + 1))
log.info('Bands (%d) : %s', len(bands), bands)
log.info('Years      : %d - %d  (%d total)', y0, y1, len(years))

# ── 2. Resolve native CRS & Scale ───────────────────────────────
proj = coll.first().select(0).projection()
info = proj.getInfo()
native_crs = info.get('crs', 'EPSG:4326')
nominal_m = proj.nominalScale().getInfo()

if native_crs.startswith('SR-ORG:'):
    grid_crs = 'EPSG:4326'
    log.warning('SR-ORG CRS (%s) -> EPSG:4326 fallback', native_crs)
elif native_crs.startswith('EPSG:'):
    grid_crs = native_crs
else:
    try:
        epsg = pyproj.CRS.from_user_input(native_crs).to_epsg()
        grid_crs = f'EPSG:{epsg}' if epsg else 'EPSG:4326'
    except Exception:
        grid_crs = 'EPSG:4326'

log.info('Output CRS: %s | Nominal Scale: %.1f m', grid_crs, nominal_m)

# ── 3. Load ROI (with dynamic simplification) ───────────────────
# Convert pixel size to degrees for the tolerance (1.5x pixel size)
tolerance_deg = (nominal_m * 1.5) / 111_320.0
roi = load_roi(SHAPEFILE_DIR, simplify_deg=tolerance_deg)

# ── 4. Output folder ────────────────────────────────────────────
short = DATASET_ID.split('/')[-1]
out_dir = os.path.join(DRIVE_ROOT, short)
os.makedirs(out_dir, exist_ok=True)
log.info('Output folder : %s', out_dir)

# ── 5. Build Exact Grid Parameters (Bypass Pyramiding) ──────────
grid_params = build_grid_params(roi, grid_crs, nominal_m)
log.info('Grid shape : %s', grid_params.get('shape_2d', '?'))

# ── 6. Year-by-year export ──────────────────────────────────────
n_ok = n_fail = n_skip = 0

for year in years:
    fname = f'{short}_{year}_{ROI_LABEL}.nc'
    final = os.path.join(out_dir, fname)

    # ── Resume: skip if file exists on Drive ──
    if os.path.exists(final) and not FORCE_OVERWRITE:
        try:
            with xr.open_dataset(final) as check_ds:
                # Verify it has time dim and expected bands
                if 'time' in check_ds.dims and len(check_ds.time) > 0:
                    sz = os.path.getsize(final)
                    log.info('[%d] On Drive (%.1f MiB) -- verified, skip', year, sz / 1024**2)
                    n_skip += 1
                    continue
        except Exception:
            log.warning('[%d] Existing file is corrupt -- re-processing', year)
            os.remove(final)
            gc.collect()
        else:
            log.info('[%d] On Drive (%.1f MiB) -- skip', year, sz / 1024**2)
            n_skip += 1
            continue

    tmp = os.path.join('/content', fname)
    done = False

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            log.info('[%d] attempt %d/%d', year, attempt, MAX_RETRIES)

            # ── Filter collection to this year ──
            yr_col = (
                ee.ImageCollection(DATASET_ID)
                .filter(ee.Filter.calendarRange(year, year, 'year'))
                .select(bands)
                .sort('system:time_start')
            )

            n_img = yr_col.size().getInfo()
            if n_img == 0:
                log.warning('[%d] 0 images -- skip year', year)
                n_skip += 1  # Fix: increment skip counter
                break

            log.info('[%d] %d image(s) in collection', year, n_img)


            # ── Open lazily via XEE ──
            # FIX: Cap chunk size to grid dimensions to prevent Errno 22
            grid_w, grid_h = grid_params.get('shape_2d', (CHUNK_XY, CHUNK_XY))
            safe_chunk = max(32, min(CHUNK_XY, grid_w, grid_h))

            ds = xr.open_dataset(
                yr_col,
                engine='ee',
                chunks={'x': safe_chunk, 'y': safe_chunk},
                **grid_params,
            )

            # Prevent duplicate timestamp crashes (GEE backend quirk)
            _, unique_idx = np.unique(ds['time'], return_index=True)
            if len(unique_idx) != ds.sizes['time']:
                log.warning('[%d] Found duplicate timestamps. Deduplicating.', year)
                ds = ds.isel(time=unique_idx)

            # ── Fix encoding & CF attributes ──
            ds = strip_xee_encoding(ds)
            ds = sanitize_attrs(ds)
            ds = make_cf_compliant(ds, DATASET_ID, ROI_LABEL, grid_crs, year)

            # ── Validate before expensive write ──
            pre_write_check(ds, year)

            # ── Write to Colab scratch ──
            enc = build_encoding(ds, COMPRESS_LEVEL, CHUNK_XY)
            log.info('[%d] Writing -> %s', year, tmp)
            t0 = time.time()

                        # ── Open lazily via XEE ──
            # Cap chunk size to grid dimensions to prevent bounds errors
            grid_w, grid_h = grid_params.get('shape_2d', (CHUNK_XY, CHUNK_XY))
            safe_chunk = max(16, min(CHUNK_XY, grid_w, grid_h))

                        # ── Write to Colab scratch ──
            enc = build_encoding(ds, COMPRESS_LEVEL, CHUNK_XY)
            log.info('[%d] Writing -> %s', year, tmp)
            t0 = time.time()

            try:
                # Reverted to netcdf4. With single-threaded Dask, this is
                # perfectly stable and avoids h5netcdf's Errno 2 bug.
                ds.to_netcdf(
                    tmp,
                    engine='netcdf4',
                    encoding=enc,
                    unlimited_dims=['time']
                )
            except Exception as e:
                if os.path.exists(tmp):
                    os.remove(tmp)
                raise RuntimeError(f'NetCDF write failed: {e}')

            dt = time.time() - t0
            mb = os.path.getsize(tmp) / 1024**2
            log.info('[%d] Written in %.0fs  (%.1f MiB)', year, dt, mb)

            dt = time.time() - t0
            mb = os.path.getsize(tmp) / 1024**2
            log.info('[%d] Written in %.0fs  (%.1f MiB)', year, dt, mb)

            if os.path.getsize(tmp) < 1024:
                raise RuntimeError(
                    f'File suspiciously small ({os.path.getsize(tmp)} B)')

            # ── Post-write integrity check ──
            ok_flag, msg = post_write_verify(tmp, bands, year)
            if not ok_flag:
                raise RuntimeError(f'INTEGRITY FAIL: {msg}')
            log.info('[%d] Integrity OK: %s', year, msg)

            # ── Export to Google Drive ──
            log.info('[%d] Exporting to Drive ...', year)
            t_mv = time.time()

            robust_drive_copy(tmp, final, max_retries=3)

            os.remove(tmp)
            log.info('[%d] Exported in %.0fs -> %s',
                     year, time.time() - t_mv, final)

            n_ok += 1
            done = True
            break

        except RuntimeError as e:
            log.error('[%d] %s', year, e)
            n_fail += 1
            break

        except Exception as e:
            log.error('[%d] %s', year, e)
            if attempt < MAX_RETRIES:
                wait = 30 * 2 ** (attempt - 1)
                log.info('[%d] retry in %ds ...', year, wait)
                time.sleep(wait)
            else:
                log.error('[%d] retries exhausted', year)
                n_fail += 1

        finally:
            # Clean up scratch on failure
            if not done and os.path.exists(tmp):
                try:
                    os.remove(tmp)
                except OSError:
                    pass

            # Aggressively free memory

            gc.collect()

# ── Summary ──────────────────────────────────────────────────────
log.info('=' * 62)
log.info('  DONE  %d ok | %d fail | %d skip  (%d years)',
         n_ok, n_fail, n_skip, len(years))
log.info('=' * 62)

# ── List files on Drive ──
if os.path.isdir(out_dir):
    nc_files = sorted(f for f in os.listdir(out_dir) if f.endswith('.nc'))
    if nc_files:
        log.info('Files on Drive (%s):', out_dir)
        for f in nc_files:
            sz = os.path.getsize(os.path.join(out_dir, f)) / 1024**2
            log.info('  %s  (%.1f MiB)', f, sz)